[project]
name = "tts-impl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torchaudio>=2.5.1",
    "numpy<2",
    "pyworld>=0.3.4",
    "torchfcpe>=0.0.4",
    "lightning>=2.4.0",
    "tensorboard>=2.18.0",
    "tqdm>=4.66.5",
    "safetensors>=0.4.5",
    "alias-free-torch>=0.0.6",
    "hydra-core>=1.3.2",
    "pytest>=8.3.3",
    "mypy>=1.11.2",
    "numba>=0.60.0",
    "cython>=3.0.11",
    "pyopenjtalk-plus>=0.3.4.post5",
    "phonemizer>=3.3.0",
    "isort>=5.13.2",
    "omegaconf>=2.3.0",
    "transformers>=4.45.2",
    "pylint>=3.3.1",
    "torch>=2.5.1",
    "black>=24.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["src/"]

[tool.hatch.build.targets.wheel]
packages = ["src/tts_impl/"]
